### ISSUE TITLE
Wrong readings for negative temperatures in Celsius

### ISSUE THREAD

**Issue by j-inner-citadel** [usbtemp/utmp-cli#1]
I have **utmp-cli** running on OpenWRT (MIPS32). 
Today I was surprised by seeing readings like these:

`# utmp-cli `
`USB Thermometer CLI v1.05 Copyright 2019 usbtemp.com Licensed under MIT licence.`
`Using serial port: /dev/ttyUSB0`
`Waiting for response ...`
`Dec 04 08:12:48 Sensor C: 4095.44`

The real temperature was bellow 0 degrees Celsius.
I fiddled with the probe precision, but that didn't make any difference.

**Comment by jaka** [comment]
I can confirm, the problem was multiplication of unsigned short `T` with -1 in function `DS18B20_acquire`. Check today's commit. Do you compile yourself?

**Comment by j-inner-citadel** [comment]
Thanks for the prompt response, @jaka.
Yes, I compile myself. Going to try and do that during the next couple of days and then report back.

**Comment by j-inner-citadel** [comment]
The bug is fixed. Sorry for taking so long to provide feedback.
