### ISSUE TITLE
Raspberry Pi support?

### ISSUE THREAD

**Issue by khaffner** [usbtemp/utmp-cli#2]
Hi!
Is this supposed to support arm architecture such as in Raspberry Pi? I'm trying to use it, but get "Exec format error", and file ./utmp-cli gives me "./utmp-cli: ELF 64-bit LSB pie executable, x86-64.......".

Could we get a version for arm? Or can I read the temperature with some other tool?

**Comment by khaffner** [comment]
I got it working with digitemp, look at https://github.com/khaffner/elbin for solution. Consider my issue solved, but would still be nice with an arm build.

**Comment by jaka** [comment]
Hello
Currently precompiled binaries are only available for x86 (Windows) and x86-64 (Linux). For Raspberry Pi (Arm) a compilation of source code is needed. I will try to prepare and test binary for RPi ASAP.
Of course, Digitemp is an alternative.

**Comment by jaka** [comment]
Hello again
I have uploaded utmp-cli for ARM arhitecture and successfully tested it on Raspberry Pi (Raspberry Pi OS). See releases.

**Comment by kinglevel** [comment]
@jaka Just tried this with rpi 2 model b, archlinux latest, got it working once, and now it "cannot find the sensor anymore". 

In lsusb i can see the device connected etc

**Comment by jaka** [comment]
@kinglevel 
Do you have any computer based on i386 or amd64 arch and check it there?
Can you check if `/dev/ttyUSB0` or maybe `/dev/ttyUSB1` is listed by `dmesg` after plugging in?

**Comment by kinglevel** [comment]
> @kinglevel
> Do you have any computer based on i386 or amd64 arch and check it there?
> Can you check if `/dev/ttyUSB0` or maybe `/dev/ttyUSB1` is listed by `dmesg` after plugging in?

Listed as ttyUSB0.

I have a rpi v4 laying around, and a virtual arch box i can try it on. so i will check dmesg and compare it.

**Comment by jaka** [comment]
@kinglevel
There was a bug, that might affect detecting sensor, fixed one year ago in version v1.062. If you can, please confirm this issue is now solved.

**Comment by kinglevel** [comment]
@jaka 

Funny that you mentioned it and replying now

I made another temp sensing project a few weeks ago, using utmp-cli v1.062, and it has been working flawlessly and reporting to my influx database now for 10 days straight.

but keep in mind that the difference i have made this time is that i have a usb hub and a raspberry 4 with raspbian. Also a crontab that reboots it every night.

I had another issues with a RTL-SDR usb stick that stopped working on soft reboots, adding a usb hub fixed the issue. And the temp sensor is on the same hub now. So something to do with usb power thingy on the PIs from what i understand it.
